config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :users, except: [:index, :destroy]
  resource :session, only: [:new, :create, :destroy]
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :details, presence: true

  belongs_to :user
end

app/models/order_day.rb
class OrderDay < ActiveRecord::Base
  after_initialize :ensure_scheduled_to_order

  validate :whitelist_is_array
  validate :blacklist_is_array
  validates :week_day_number, presence: true
  validates_uniqueness_of :week_day_number, :scope => :user_id

  belongs_to :user

  def whitelist
    super.join ', '
  end

  def blacklist
    super.join ', '
  end

  def whitelist=(value)
    super(value.split(/, |,/))
  end

  def blacklist=(value)
    super(value.split(/, |,/))
  end

  def week_day_word
    {
      1 => 'Monday',
      2 => 'Tuesday',
      3 => 'Wednesday',
      4 => 'Thursday',
      5 => 'Friday'
    }[week_day_number]
  end

  def user_profile_display_css
    scheduled_to_order? ? 'background-color: #90EE90;' : 'background-color: #C0C0C0;'
  end

  private

  def whitelist_is_array
    whitelist.blank? || whitelist.is_a?(Array)
  end

  def blacklist_is_array
    blacklist.blank? || blacklist.is_a?(Array)
  end

  def ensure_scheduled_to_order
    return unless scheduled_to_order == nil

    scheduled_to_order = true
  end
end

app/models/ordered_item.rb
class OrderedItem < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :create_order_days_for_user
  after_initialize :ensure_session_token

  validates :mealpal_email, :mealpal_password, :session_token, presence: true
  validates_uniqueness_of :mealpal_email
  validates_format_of :mealpal_email, :with => /@/

  has_many :ordered_items, dependent: :destroy
  has_many :order_days, dependent: :destroy
  has_many :events, dependent: :destroy

  accepts_nested_attributes_for :order_days

  def create_order_days_for_user
    return unless order_days.blank?

    1.upto(5) do |day_number|
      order_days.build(week_day_number: day_number)
    end
  end

  def self.find_by_credentials(mealpal_email, mealpal_password)
    user = User.find_by(mealpal_email: mealpal_email)

    if user
      user.mealpal_password == mealpal_password ? user : nil
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def order_early?
    early_order
  end

  private

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in!(user)
    user.reset_session_token!

    session[:session_token] = user.session_token
  end

  def log_out!
    current_user.reset_session_token!

    session[:session_token] = nil

    current_user.reload
  end

  def redirect_current_user
    redirect_to user_path(current_user) if current_user
  end

  def redirect_signed_out_user
    redirect_to root_path unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_current_user

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_signed_out_user, only: [:destroy]
  before_action :redirect_current_user, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(mealpal_email, mealpal_password)

    if @user
      log_in!(@user)

      redirect_to user_path(@user)
    else
      flash.now[:error] = "Oops, can't find that user!"

      @user = User.new(mealpal_email: mealpal_email)
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!

    session[:session_token] = nil

    redirect_to root_url
  end

  private

  def mealpal_email
    params[:user][:mealpal_email]
  end

  def mealpal_password
    params[:user][:mealpal_password]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_signed_out_user, only: [:show, :edit, :update]

  def new
    log_out! if current_user

    @user = User.new(address: '22 West 19th Street, New York, NY, United States')
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)

      flash[:message] = "success, record created!"

      UserMailer.send_signup_email(@user).deliver_now!

      redirect_to user_path(@user)
    else
      flash.now[:error] = 'oh no, check the fields'

      render :new
    end
  end

  def show
    if params[:id].to_i != current_user.id
      redirect_to user_path(current_user)
    end

    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:message] = 'success, record updated!'

      redirect_to user_path(@user)
    else
      flash.now[:error] = 'oh no, check the fields'

      render :edit
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(
        :mealpal_email,
        :mealpal_password,
        :address,
        :early_order,
        order_days_attributes: [:id, :scheduled_to_order, :whitelist, :blacklist, :week_day_number]
      )
  end
end

app/views/home/index.html.slim
div.jumbotron
  h1 style='text-align: center;'
    ' Welcome to Mealpal Orderer

  div style=''
    div.col-md-6.col-lg-6
      = image_tag "mealpal_orderer_gifs/#{(1..5).to_a.sample}.gif", class: 'mealpal-gif'

    div.row style='padding-top: 48px;'
      div.col-xs-6.col-md-3
        = link_to new_session_path, class: 'thumbnail' do
          h2 style='text-align: center;'
            ' Log In
      div.col-xs-6.col-md-3
        = link_to new_user_path, class: 'thumbnail' do
          h2 style='text-align: center;'
            ' Sign Up

.page-header
  h4
    | Mealpal Orderer orders Mealpal for you automatically based on your meal preferences. Take the hassle away and never forget to order Mealpal again!

app/views/layouts/application.html.slim
doctype html
html
  head
    title Mealpal Orderer
    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    a href="https://github.com/petrgazarov/mealpal-orderer"
      img[
          style="position: absolute; top: 0; left: 0; border: 0;"
          src="https://camo.githubusercontent.com/82b228a3648bf44fc1163ef44c62fcc60081495e/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f7265645f6161303030302e706e67"
          alt="Fork me on GitHub"
          data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_red_aa0000.png"
         ]

    - if logged_in?
      = button_to 'Log out',
                  '/session',
                  class: 'btn btn-primary btn-lg',
                  method: :delete,
                  style: 'float: right; margin: 12px 24px 0 0;'

    .container style='padding-top: 56px'

      - if flash[:message]
        h2.alert.alert-success
          = flash[:message]
      - if flash[:error]
        h2.alert.alert-danger
          = flash[:error]

      = yield

app/views/users/_full_form.html.slim
= simple_form_for user,
                  url: path,
                  method: method do |f|

  = f.input :address,
            required: true,
            input_html: { class: 'form-control' },
            wrapper_html: { class: 'col-lg-12 col-md-12 col-sm-12', style: 'padding-bottom: 15px;' },
            placeholder: 'Enter your address'

  br

  = f.label 'Mealpal credentials',
    required: true,
    class: 'col-lg-12 col-md-12 col-sm-12'

  br

  .clearfix
    = f.input :mealpal_email,
              type: :email,
              required: true,
              input_html: { class: 'form-control' },
              wrapper_html: { class: 'col-lg-6 col-md-6 col-sm-6' },
              label: false,
              placeholder: 'Mealpal email'

    = f.input :mealpal_password,
              type: :password,
              required: true,
              input_html: { class: 'form-control' },
              wrapper_html: { class: 'col-lg-6 col-md-6 col-sm-6' },
              label: false,
              placeholder: 'Mealpal password'

  br
  br
  br

  .clearfix
    | I usually run either at 5pm or 11pm the day before. Check the box below if you would like to stay ahead of the crowd.
    .checkbox.checkbox-primary
      = f.check_box :early_order,
                    label: false,
                    wrapper: false,
                    id: 'checkbox_early_order',
                    checked: f.object.early_order

      = f.label 'early order - 5pm',
                 for: 'checkbox_early_order'

  br
  br

  .panel.panel-default
    .panel-body
      | For each day, you can enter a whitelist and a blacklist. You can reference both meal names and restaurant names.
      br
      | Enter values separated by commas, e.g. "Sandwich, Salad, Aleo Restaurant".

  = f.simple_fields_for :order_days do |ff|
    = ff.input :week_day_number,
               as: :hidden

    .checkbox.checkbox-primary style='padding-top: 20px; display: flex; justify-content: row'
      = ff.check_box :scheduled_to_order,
                     label: false,
                     wrapper: false,
                     id: "checkbox#{ff.object.week_day_number}",
                     checked: ff.object.scheduled_to_order

      = ff.label ff.object.week_day_word,
                 for: "checkbox#{ff.object.week_day_number}"

    = ff.input :whitelist,
               as: :string,
               input_html: { class: 'form-control', value: ff.object.whitelist },
               wrapper_html: { class: 'col-lg-6 col-md-6 col-sm-6' },
               label: false,
               placeholder: 'Whitelist (optional)'

    = ff.input :blacklist,
               as: :string,
               input_html: { class: 'form-control', value: ff.object.blacklist },
               wrapper_html: { class: 'col-lg-6 col-md-6 col-sm-6' },
               label: false,
               placeholder: 'Blacklist (optional)'

  .input-group-btn style='padding-top: 20px'
    = f.submit 'Submit',
               class: 'btn btn-primary btn-lg'

app/views/users/edit.html.slim
.col-sm-12.col-xs-12
  h1 style='text-align: center;'
    ' Edit your info

  br

  = render 'users/full_form',
           user: @user,
           path: user_path(@user),
           method: :patch

app/views/users/new.html.slim
.col-sm-12.col-xs-12
  h1 style='text-align: center;'
    ' Sign up to order your lunch

  br

  .panel.panel-default
    .panel-body
      | Enter your Mealpal credentials below and I will order a random mealpal for you for the days you select. 
      br
      br
      ul
        li If I find out that you already ordered by then, I'll just stop there. 
        li If you've used the maximum number of meals for the current cycle, I also won't do anything.

  = render 'users/full_form',
           user: @user,
           path: users_path,
           method: :post

  br
  br

  div class='well well-sm'
    p Note:

    p Your password is stored as plain text. There is no public access to the database, however I recommend using a unique password that you don't use anywhere else.

app/views/users/show.html.slim
.col-sm-12.col-xs-12
  h1 style='text-align: center;'
    ' Hey,
    = @user.mealpal_email

  .panel.panel-default
    .panel-body
      h3 style='text-align: center;'
        | Basic Info

      h4 Email:
      h5 = @user.mealpal_email

      h4 Address:
      h5 = @user.address

      h4 Pick up time:
      h5 12:00pm-12:15pm

      h4 Run orderer at:
      h5 = @user.early_order ? '5pm' : '11pm'

      div
        = link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary btn-lg'

      h3 style='text-align: center;'
        | Meal preferences

      br

      div.show-order-days
        - @user.order_days.order(:week_day_number).each do |order_day|
          .panel.panel-default.col-xs-12.col-sm-12 style="#{order_day.user_profile_display_css}"
            .panel-body
              div
                h4
                  = order_day.week_day_word

                p
                  ' Whitelist:
                  = order_day.whitelist
                p
                  ' Blacklist:
                  = order_day.blacklist

      div style='clear: both;'
        = link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary btn-lg'